#!/usr/bin/env python3
"""Fail-closed cross-file version agreement check for release automation.

Compares ``--expected-version`` against every declared source of truth for
the project's version number and, optionally, the Git tag format and the
release-manifest generated by scripts/release_artifacts.py. Every check
runs and every failure is collected and reported; the script exits
non-zero if any check fails (fail closed), so a single mismatch blocks
the release rather than being silently ignored.

See docs/RELEASE.md for the full release procedure this gates.
"""

from __future__ import annotations

import argparse
import importlib
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TAG_PATTERN = re.compile(r"^v(\d+\.\d+\.\d+)$")


class VersionCheckError(RuntimeError):
    """Raised by an individual check; collected and reported by main()."""


def _read_text(path: Path) -> str:
    if not path.is_file():
        raise VersionCheckError(f"required file missing: {path}")
    return path.read_text(encoding="utf-8")


def check_version_py(expected: str) -> None:
    sys.path.insert(0, str(REPO_ROOT))
    module = importlib.import_module("blender_mobile_3d.version")
    importlib.reload(module)
    actual = module.VERSION
    if actual != expected:
        raise VersionCheckError(
            f"blender_mobile_3d/version.py: VERSION={actual!r} != expected {expected!r}"
        )


def check_bl_info(expected: str) -> None:
    sys.path.insert(0, str(REPO_ROOT))
    module = importlib.import_module("blender_mobile_3d")
    importlib.reload(module)
    actual = ".".join(str(part) for part in module.bl_info["version"])
    if actual != expected:
        raise VersionCheckError(
            f"blender_mobile_3d.bl_info['version']: {actual!r} != expected {expected!r}"
        )


def check_blender_manifest_toml(expected: str) -> None:
    path = REPO_ROOT / "blender_manifest.toml"
    data = tomllib.loads(_read_text(path))
    actual = data.get("project", {}).get("version")
    if actual != expected:
        raise VersionCheckError(
            f"blender_manifest.toml: version={actual!r} != expected {expected!r}"
        )


def check_npm_package_json(expected: str) -> None:
    path = REPO_ROOT / "installers" / "npm" / "package.json"
    data = json.loads(_read_text(path))
    actual = data.get("version")
    if actual != expected:
        raise VersionCheckError(
            f"installers/npm/package.json: version={actual!r} != expected {expected!r}"
        )


def check_python_installer_pyproject(expected: str) -> None:
    path = REPO_ROOT / "installers" / "python" / "pyproject.toml"
    data = tomllib.loads(_read_text(path))
    actual = data.get("project", {}).get("version")
    if actual != expected:
        raise VersionCheckError(
            f"installers/python/pyproject.toml: version={actual!r} != expected {expected!r}"
        )


def check_release_manifest(expected: str, manifest_path: Path) -> None:
    data = json.loads(_read_text(manifest_path))
    actual = data.get("version")
    if actual != expected:
        raise VersionCheckError(f"{manifest_path}: version={actual!r} != expected {expected!r}")


def parse_tag(tag: str) -> str:
    """Return the bare version from a ``vX.Y.Z`` tag; raises on bad format."""
    match = TAG_PATTERN.fullmatch(tag)
    if not match:
        raise VersionCheckError(
            f"git tag {tag!r} does not match the required pattern v<major>.<minor>.<patch>"
        )
    return match.group(1)


def check_tag_reachable_from_main(commit: str, main_ref: str) -> None:
    # git resolved via PATH; fixed argument array, no shell.
    result = subprocess.run(  # noqa: S603
        ["git", "merge-base", "--is-ancestor", commit, main_ref],  # noqa: S607
        cwd=REPO_ROOT,
        check=False,
    )
    if result.returncode != 0:
        raise VersionCheckError(
            f"commit {commit} is not reachable from {main_ref}; "
            "refusing to release from an untrusted ref"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--expected-version", required=True, help="e.g. 1.0.0")
    parser.add_argument(
        "--git-tag", default=None, help="e.g. v1.0.0; also checked against --expected-version"
    )
    parser.add_argument(
        "--release-manifest",
        type=Path,
        default=None,
        help="Path to a generated release-manifest.json",
    )
    parser.add_argument(
        "--require-main-ancestor",
        default=None,
        metavar="REF",
        help="Fail unless --commit is reachable from this ref (e.g. origin/main)",
    )
    parser.add_argument("--commit", default="HEAD")
    args = parser.parse_args()

    expected = args.expected_version
    errors: list[str] = []

    def run(check_name: str, fn) -> None:
        try:
            fn()
        except VersionCheckError as exc:
            errors.append(f"{check_name}: {exc}")

    if args.git_tag:
        run("git tag format", lambda: parse_tag(args.git_tag))
        tag_version = args.git_tag[1:] if args.git_tag.startswith("v") else args.git_tag
        if tag_version != expected:
            errors.append(f"git tag: tag-derived version {tag_version!r} != expected {expected!r}")

    run("blender_mobile_3d/version.py", lambda: check_version_py(expected))
    run("blender_mobile_3d bl_info", lambda: check_bl_info(expected))
    run("blender_manifest.toml", lambda: check_blender_manifest_toml(expected))
    run("installers/npm/package.json", lambda: check_npm_package_json(expected))
    run("installers/python/pyproject.toml", lambda: check_python_installer_pyproject(expected))

    if args.release_manifest is not None:
        run(
            "release-manifest",
            lambda: check_release_manifest(expected, args.release_manifest),
        )

    if args.require_main_ancestor is not None:
        run(
            "tag reachability",
            lambda: check_tag_reachable_from_main(args.commit, args.require_main_ancestor),
        )

    if errors:
        print("verify_release_versions: FAILED", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    print(f"verify_release_versions: all sources agree on version {expected!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
